#!/bin/bash

for modfile in $(dirname $(modinfo -n vboxdrv))/*.ko; do
  echo "Signing $modfile"
  /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 \
                                /root/module-signing/MOK.priv \
                                /root/module-signing/MOK.der "$modfile"
done

for modfile in $(dirname $(modinfo -n vboxnetflt))/*.ko; do
  echo "Signing $modfile"
  /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 \
	  			/root/module-signing/MOK.priv \
				/root/module-signing/MOK.der "$modfile"
done

for modfile in $(dirname $(modinfo -n vboxnetadp))/*.ko; do
  echo "Signing $modfile"
  /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 \
	  			/root/module-signing/MOK.priv \
				/root/module-signing/MOK.der "$modfile"
done

for modfile in $(dirname $(modinfo -n vboxpci))/*.ko; do	
  echo "Signing $modfile"
  /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 \
	  			/root/module-signing/MOK.priv \
				/root/module-signing/MOK.der "$modfile"
done
